### ISSUE TITLE
Figure out why master is broken

### ISSUE THREAD

**Issue by kellyselden** [tomdale/ember-cli-addon-tests#87]
Tracking issue

**Comment by trentmwillis** [comment]
Tried running tests locally and they just seem to hang forever (same behavior as CI). I'll be investigating this as we need to fix other aspects of this addon as well.

**Comment by simonihmig** [comment]
Saw the same today when investigating some broken tests:

* for ember-cli 2.12 I *think* the problem might be that there was some interactive prompt when running `ember new` asking if some `.eslintrc.js` file should be overridden (because the blueprint explicitly installed `ember-cli-eslint` running its own blueprint, instead of just adding it to `package.json`. I think that has been changed meanwhile). I assume this interactive prompt just hangs up the command, waiting infinitely for some input...
* for ember-cli 2.13 I same some problem related to the fact that there is no `bower.json`. Probably related to #75 

Just my first impressions, will also have to dig deeper into it...

**Comment by trentmwillis** [comment]
`master` is all green again!
